//constantes  
export const GET_VIDEOGAMES = "GET_VIDEOGAMES"
export const FILTER_VIDEOGAMES_GENRE = "FILTER_VIDEOGAMES_GENRE"
export const FILTER_CREATED = "FILTER_CREATED"
export const FILTER_RATING = "FILTER_RATING"
export const FILTER_AS_DES = "FILTER_AS_DES"
export const GET_BY_NAME = "GET_BY_NAME"
export const GET_BY_ID = "GET_BY_ID"